networks:
  moodle-network:
    driver: bridge
services:
  moodle-db:
    image: 'postgres:16-alpine'
    container_name: moodle-db
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_PORT: 5432
    networks:
      - moodle-network
    ports:
      - '8432:5432'
    volumes:
      - '/services/volumes/moodle-app/moodle-db:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres -d moodle'
      interval: 10s
      timeout: 5s
      retries: 5
  moodle-app:
    image: docker.io/bitnami/moodle:5.0
    container_name: moodle-app
    restart: always
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=moodle-db
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=
      - MOODLE_DATABASE_NAME=
      - MOODLE_DATABASE_PASSWORD=
      - MOODLE_USERNAME=
      - MOODLE_PASSWORD=
      - MOODLE_EMAIL=noreply@tetonsoftware.dev
      - 'MOODLE_SITE_NAME=Kool Skool'
    networks:
      - moodle-network
    volumes:
      - '/services/volumes/moodle-app/moodle:/bitnami/moodle'
      - '/services/volumes/moodle-app/moodledata:/bitnami/moodledata'
    ports:
      - '8082:8080'
    labels:
      - traefik.enable=true
      - traefik.http.routers.moodle.rule=Host(`school.tetonsoftware.cloud`)
      - traefik.http.routers.moodle.tls.certresolver=letsencrypt
      - traefik.http.services.moodle.loadbalancer.server.port=8080
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://127.0.0.1:8080 || exit 1'
      interval: 15s
      timeout: 10s
      retries: 3
