services:
  moodle-db:
    image: postgres:16-alpine
    container_name: moodle-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  moodle-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle-app
    env_file:
      - .env
      #restart: always
    environment:
      MOODLE_BRANCH: ${MOODLE_BRANCH}
      MOODLE_DB_TYPE: ${DB_TYPE}
      MOODLE_DB_HOST: moodle-db:5432
      MOODLE_DB_NAME: ${POSTGRES_DB}
      MOODLE_DB_USER: ${POSTGRES_USER}
      MOODLE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      MOODLE_SITE_NAME: ${SITE_NAME}
      MOODLE_SITE_URL: "https://${DOMAIN}"
    command: |
      /bin/bash -c "
        echo 'Setting permissions for /moodledata...';
        chown -R www-data:www-data /moodledata;
        chmod -R 775 /moodledata;
        chmod -R g+s /moodledata;
        echo 'ServerName ${DOMAIN}' >> /etc/apache2/apache2.conf;
        apache2-foreground
      "

    labels:
      - "traefik.enable=true"

      # HTTP Router (Redirect HTTP to HTTPS)
      - "traefik.http.routers.moodle-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.moodle-http.entrypoints=web"
      - "traefik.http.routers.moodle-http.middlewares=https-redirect"

      # Middleware for HTTP to HTTPS Redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

      # HTTPS Router
      - "traefik.http.routers.moodle-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.moodle-https.entrypoints=websecure"
      - "traefik.http.routers.moodle-https.tls=true"
      - "traefik.http.routers.moodle-https.tls.certresolver=le"
      - "traefik.http.routers.moodle-https.service=moodle-service"

      # Service Definition
      - "traefik.http.services.moodle-service.loadbalancer.server.port=80"

    volumes:
      - ${MOODLE_DATA_PATH}:/moodledata
    ports:
      - '8082:80'
    depends_on:
      - moodle-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
